"""empty message

Revision ID: 789380b306ec
Revises: 
Create Date: 2019-04-24 14:57:38.094945

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '789380b306ec'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('candidate',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('enrolement_no', sa.String(length=50), nullable=True),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('address', sa.String(length=80), nullable=True),
    sa.Column('degree_name', sa.String(length=80), nullable=True),
    sa.Column('admission_status', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('enrolement_no')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('candidate')
    # ### end Alembic commands ###
